apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-openai-key
  namespace: ai-demo
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ${MANAGED_IDENTITY_CLIENT_ID}
    keyvaultName: ${KEY_VAULT_NAME}
    objects:  |
      array:
        - |
          objectName: openai-key
          objectType: secret
          objectAlias: OpenAIAPIKey
    tenantId: ${TENANT_ID}